services:
  kopi-teh:
    build: .
    container_name: kopi-teh
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kopi-teh.rule=Host(`yourdomain.com`)"
      - "traefik.http.routers.kopi-teh.entrypoints=websecure"
      - "traefik.http.routers.kopi-teh.tls.certresolver=letsencrypt"
      - "traefik.http.services.kopi-teh.loadbalancer.server.port=80"
    networks:
      - traefik

networks:
  traefik:
    external: true
